[package]
name = "pulsar_docs"
version = "0.1.0"
edition = "2024"

[dependencies]
rust-embed = { version = "6", features = ["interpolate-folder-path"] }
once_cell = "1.19"

[build-dependencies]
rustdoc-md = "0.1"
serde_json = "1.0"

[lints]
workspace = true
